### ISSUE TITLE
sample?

### ISSUE THREAD

**Issue by mumin16** [mstahl3/MetaStockDB#1]
sample?

**Comment by mumin16** [comment]
char curdir[256];
	getcwd(curdir, 256);
	std::string msdir = curdir;
	msdir.append("\\DAILYMSDIR");
	MetaStockDB* ms = new MetaStockDB(msdir, false, 0);
	Equity *stock = ms->find(".DJI");
	Date date; Time time; float open, close, high, low; unsigned long volume; float openInterest;

	std::cout << stock->description();
       stock->getFirstTradingDayData(date, time, open, close, high, low, volume, openInterest);
	do
	{
		int Month = date.Month(); int day= date.day();
		std::cout << "Date: " << date.Year() << Month << day;
		std::cout << " Time: " << time;
		std::cout << " Open: " << open;
		std::cout << " Close: " << close;
		std::cout << " High: " << high;
		std::cout << " Low: " << low;
		std::cout << " Volume: " << volume;
		std::cout << " OI: " << openInterest << std::endl;

	} while (stock->getNextTradingDayData(date, time, open, close, high, low, volume, openInterest));

**Comment by mstahl3** [comment]
I added 2 demo's, one of which finds the stock by symbol name, and then prints one of the attributes of that stock.  Be sure to download the latest code to get access to new functions used in the demo.

(The second demo can be used to dump all stocks help in a DB).
