### ISSUE TITLE
expression did not evaluate to a constant- c++

### ISSUE THREAD

**Issue by mumin16** [mstahl3/MetaStockDB#3]
msfileio.cpp line 41,83,101:
unsigned char buffer[numBytesToRead]; // Buffer to hold read bytes

Is a Variable Length Array and is not standard in C++. Some compilers like GCC allow them as an extensions but MSVS will not compile them.

In order to get a dynamic array you will need to use a pointer and new

char* buffer = new char[numBytesToRead];

**Comment by mstahl3** [comment]
I converted all VLA's to dynamic array to support compilation under Windows.
